apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: helper
  name: helper
spec:
  containers:
  - env:
    - name: DB_CONNECTION
      value: mysql
    - name: DB_DATABASE
      value: helper
    - name: DB_HOST
      value: sqldb
    - name: DB_PASSWORD
      value: helper
    - name: DB_PORT
      value: "3306"
    - name: DB_USERNAME
      value: helper
    - name: MAIL_ENCRYPTION
      value: tls
    - name: MAIL_HOST
      value: smtp.gmail.com
    - name: MAIL_MAILER
      value: smtp
    - name: MAIL_PASSWORD
      value: jjscktfmiwbkuvzx
    - name: MAIL_PORT
      value: "587"
    - name: MAIL_USERNAME
      value: tech@headsupcorporation.com
    - name: PUSHER_APP_CLUSTER
      value: ap2
    - name: PUSHER_APP_ID
      value: "1923748"
    - name: PUSHER_APP_KEY
      value: fb18167233b2d2c8139a
    - name: PUSHER_APP_SECRET
      value: d982e4edf2eb1a3619ec
    - name: PUSHER_HOST
      value: ws.pusherapp.com
    - name: PUSHER_PORT
      value: "443"
    - name: PUSHER_SCHEME
      value: https
    image: hcorptech/helper:latest
    name: helper-server
    ports:
    - containerPort: 8000
    resources: {}
    volumeMounts:
    - mountPath: /etc/localtime
      name: helper-claim0
  restartPolicy: Never
  volumes:
  - name: helper-claim0
    persistentVolumeClaim:
      claimName: helper-claim0
status: {}
